version: '3.1'

services:

  php8:
    image: ${APP_IMAGE}
    container_name: ${CONTAINER_NAME}
    restart: on-failure
    volumes:
      - ../:/application
    working_dir: /application
    command: [tail, '-f', /dev/null]
